### ISSUE TITLE
long polling race conditions / missing events

### ISSUE THREAD

**Issue by halfbaked** [smaldini/grails-events-push#10]
Ok, so not necessarily within the scope of this plugin, but something to consider for sure. 

When two events were triggered from the one action, only one would find its way to the server. Lets take objects SupportTicket and Comment. Now lets say I create a comment which simultaneously closes the Ticket. This could trigger one event for the new Comment, and another event for the updated Ticket. I only ever saw one of these two events, and which one the client saw was indeterminate. I believe the reason to be that moment where the server sends its response for the first event, the second event fires, but because there is no request waiting for the second event, it is not broadcast to the client. Delaying one of the events does seem to solve the issue, but probably not an ideal solution.

**Comment by smaldini** [comment]
I used a the atmosphere header cache for that but I may have screwed something, let me have a look

**Comment by smaldini** [comment]
Did you have a try with the last snapshot (yesterday) ?

**Comment by halfbaked** [comment]
Hey Stephane, 
I haven't forgotten about this, but have yet to get to it. 
I'll update the ticket once I do!

**Comment by halfbaked** [comment]
Hey Stephane, 

Finally getting back into this. M2.Snapshot is compiling fine, but with .M1 I get compilation errors that seem to indicate some kind of misalignment with the version of platform-core. It could just be me!

To the specific issue, I don't think it is fixed, and I'll share why with a different example. I have a list of tickets. When I create a ticket, I don't update the list immediately on the client. I let a server event do it for me. With long-polling, the client doesn't always see the event. It seems to depend on whether the connection in a state of reconnecting or not. It makes logical sense of course. Anyway, I dropped the long-polling option, and now web sockets are being used by default, and it is working fine. So maybe not a big deal.

**Comment by smaldini** [comment]
Well, even long-polling should work (caching non dispatched message until reconnection). So there is a bug for sure to fix. I strongly advise 'sse' or 'streaming' transport (which are the default if websocket is not supported now).

ServerSideEvent works fine on cloudfoundry, see http://grailstodos.cloudfoundry.com/todos . I'll try to find time for investigation on what's happening with Header cache.

**Comment by smaldini** [comment]
Just in case I have another snapshot released, I have not tested against this issue however but since I've updated something related (message size tracking).
