### ISSUE TITLE
JavaScript event handler is somehow invoked twice

### ISSUE THREAD

**Issue by ruado1987** [smaldini/grails-events-push#12]
After upgrading to 1.0.M2-SNAPSHOT, my event handler on a particular topic was surprisingly executed twice whenever an event occurs on the topic. Since I noticed there is a significant change in grailsEvents.js between version 1.0.M1-SNAPSHOT and 1.0.M2-SNAPSHOT, I tried to configure grails to use the grailsEvent.js copied from the former. Surprisingly, my event handler is now called only once per event. So i am suspecting that there is a bug in the current version of grailsEvents.js. Has anyone come across this issue?

**Comment by smaldini** [comment]
Any chances to get steps to reproduces ?

**Comment by ruado1987** [comment]
I will create a small example reproducing the problem and post it to the grails mailing list. Thanks.

**Comment by Eylen** [comment]
Hello, I think I'm experiencing a similar problem, but just in Internet Explorer (testes with version 8 and 9). 
I'm using M7 of this plugin. How did you fix this?
Also check my question in stackoverflow http://stackoverflow.com/questions/14960452/grails-event-push-sending-event-twice-or-not-sending-in-ie8

**Comment by ruado1987** [comment]
Hi Eylen, please consult [this thread](http://grails.1312388.n4.nabble.com/Issue-with-grails-events-push-plugin-td4633074.html#a4633157), which helped me to sort out the problem.

**Comment by Eylen** [comment]
Hello, I've tried the suggestion to put transport:"sse", but still the events are not reaching to ie and in Chrome I get this error in the console: Uncaught Error: SecurityError: DOM Exception 18 
Any suggestion?
