### ISSUE TITLE
Websocket connection not established - fallback to long-polling every time

### ISSUE THREAD

**Issue by ClemensSchneider** [smaldini/grails-events-push#15]
Hi,

It seems that I'm not able to get a websocket-connection working using Chrome (21), Chrominium (18) and Firefox (14) under Ubuntu 11.10 and Grails 2.1.0, events-push 1.0.M2.
Tomcat NIO support is off (same behaviour with NIO enabled though).

See https://github.com/ClemensSchneider/grails-events-push-tester for a basic grails 2.1.0 app. You may clone it, launch it via grailsw (grails wrapper), open the development-tools and browse to `http://localhost:8080/push-tester`. There you have a button to subscribe (once) and send an event (setup as described in the grails-events-push readme).

What I am seeing in all browsers is that a websocket-connection upgrade is requested but as soon as I try to register for an event or try to send an event, the websocket-connection is closed and being downgraded to long-polling:

```
WebSocket is closed before the connection is established. :8080:1
Websocket failed. Downgrading to Comet and resending {"topic":"saveTodo","body":{"hello":"World"}} jquery.atmosphere.js:2297
Websocket closed, reason: Unknown: no status code was provided even though one was expected. jquery.atmosphere.js:2297
Websocket closed, wasClean: true jquery.atmosphere.js:2297
Websocket closed normally jquery.atmosphere.js:2297
```

Request and response when creating the `grails.Events` instance look like the following:

```
Request URL:ws://localhost:8080/push-tester/g-eventsbus/eventsbus?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=1.0&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&topics=eventsbus
Request Method:GET
Status Code:101 Switching Protocols

Request Headers

Connection:Upgrade
Host:localhost:8080
Origin:http://localhost:8080
Sec-WebSocket-Extensions:x-webkit-deflate-frame
Sec-WebSocket-Key:LmwF9EHgvsMubhChVx0yMQ==
Sec-WebSocket-Version:13
Upgrade:websocket
(Key3):00:00:00:00:00:00:00:00
Query String Parametersview URL encoded
X-Atmosphere-tracking-id:0
X-Atmosphere-Framework:1.0
X-Atmosphere-Transport:websocket
X-Atmosphere-TrackMessageSize:true
X-Cache-Date:0
topics:eventsbus

Response Headers

Connection:upgrade
Date:Fri, 17 Aug 2012 06:56:55 GMT
Sec-WebSocket-Accept:uYV8WubfjVXRGoDKnnFQYM+508A=
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
Upgrade:websocket
X-Atmosphere-tracking-id:87cf5b84-c565-456c-b041-ab4581ba66f7
(Challenge Response):00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
```

When I'm creating `new grails.Events("http://localhost:8080/push-tester")` without registering or sending anything over the wire, I can see, that there are frames (`2<@>{}`) sent by the server in intervals of 10 seconds, but after one minute, the connection seems to get terminated, a reconnect is initiated and the following is printed to the console (chrome):

```
Websocket closed, reason: The endpoint is terminating the connection due to a protocol error. (jquery.atmosphere.js:2297)
Websocket closed, wasClean: true
```

This repeats itself (endlessly?).

**Comment by smaldini** [comment]
Known issue, I need to play with it. Maybe an underlying issue with atmosphere. Thank you for the test case it will help !

**Comment by ClemensSchneider** [comment]
Hey,
any news on this? Did you have time to figure it out?

**Comment by smaldini** [comment]
I need to test with Atmosphere 1.0, will work on that next week since I'm
pretty busy this we :(

On Fri, Sep 7, 2012 at 9:13 AM, ClemensSchneider
notifications@github.comwrote:

> Hey,
> any news on this? Did you have time to figure it out?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/15#issuecomment-8359037.

## 

## _Stéphane MALDINI_

**Comment by ClemensSchneider** [comment]
Ok, thanks a lot for your efforts! :)

**Comment by ClemensSchneider** [comment]
Updates:
What I tried is to use latest Tomcat 7.0.30 + Atmosphere 1.0 libraries with the same results. Using the Jetty-Plugin did not work for me, as an exception was raised during startup (which isn't related to events-push though).

**Comment by smaldini** [comment]
Can you test with the upcoming M3 release (release in progress)

**Comment by ClemensSchneider** [comment]
Tested it but still can't get it to work. I wonder if it's only me having this issue or if others do encounter it too?

Server-side log-entries when instantiating the client-side event-bus:

```
2012-10-02 10:49:46,832 [http-nio-8080-exec-5] DEBUG http11.InternalNioInputBuffer  - Received [GET /push-tester/g-eventsbus/eventsbus?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=1.1&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&topics=eventsbus HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:8080
Origin: http://localhost:8080
Sec-WebSocket-Key: yVdpsaIVNMIXOtdgR55UmA==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: x-webkit-deflate-frame

]
2012-10-02 10:49:46,832 [http-nio-8080-exec-5] DEBUG connector.CoyoteAdapter  - The variable [uriBC] has value [/push-tester/g-eventsbus/eventsbus]
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG connector.CoyoteAdapter  - The variable [semicolon] has value [-1]
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG connector.CoyoteAdapter  - The variable [enc] has value [UTF-8]
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG buf.B2CConverter  - B2CConverter: Converted: /push-tester/g-eventsbus/eventsbus
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG buf.B2CConverter  - B2CConverter: EOF
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG http.Parameters  - Set encoding to ISO-8859-1
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG http.Parameters  - Decoding query null UTF-8
2012-10-02 10:49:46,833 [http-nio-8080-exec-5] DEBUG http.Parameters  - Start processing with input [X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=1.1&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&topics=eventsbus]
2012-10-02 10:49:46,835 [http-nio-8080-exec-5] DEBUG websocket.DefaultWebSocketProcessor  - Atmosphere detected WebSocket: org.atmosphere.container.version.TomcatWebSocket
2012-10-02 10:49:55,704 [http-nio-8080-exec-4] DEBUG http11.Http11NioProcessor  - Error parsing HTTP request header
Message: Unexpected EOF read on the socket
    Line | Method
->> 1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    603 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread
2012-10-02 10:49:55,705 [http-nio-8080-exec-4] DEBUG threads.LimitLatch  - Counting down[http-nio-8080-exec-4] latch=8
```

**Comment by ClemensSchneider** [comment]
Do you have any idea what the issue could be here so that I may try to dig-in myself? Any hints what would be worth looking at?

**Comment by zyro23** [comment]
same problem here. also, id like to know the config with which websocket are expected to work (bio/nio? servlet2.5/3.0? browser?)

**Comment by fletchgqc** [comment]
When using the atmosphere plugin directly I noticed that the pre-1.0 versions of the atmosphere library didn't work, but for example in 1.0.7 websocket works fine with Chrome (using servlet 3.0).
