### ISSUE TITLE
Triggering server-side event as described does not work

### ISSUE THREAD

**Issue by ClemensSchneider** [smaldini/grails-events-push#16]
Hi,

following the readme I tried triggering server side events in a service using `event('savedTodo', data)`. 
When debug is enabled you can see the following log-entry (which should be level WARN I guess :) ):
`2012-08-17 09:32:58,582 [grailsTopicExecutor-10] DEBUG registry.DefaultEventsRegistry  - Failing call to class MyService.saveTodo with args {hello=World, moreData=There we go....} : java.lang.reflect.InvocationTargetException`

It starts working when I use `event('savedTodo', data, {})` (with a closure-callback as third parameter).

**Comment by smaldini** [comment]
Super weird, let me test asap. Btw what is your Listener signature ?

**Comment by ClemensSchneider** [comment]
The service looks like the following:

Works:

```
import grails.events.Listener

class MyService {
    //will receive client events from 'saveTodo' topic
    @Listener(namespace='browser') 
    def saveTodo(Map data){
        log.info(data)
        data.moreData = "There we go...."
        event('savedTodo', data, {}) // will trigger registered browsers on 'savedTodo' topic
    }
}

```

Does not work:

```
import grails.events.Listener

class MyService {
    //will receive client events from 'saveTodo' topic
    @Listener(namespace='browser') 
    def saveTodo(Map data){
        log.info(data)
        data.moreData = "There we go...."
        event('savedTodo', data) // will trigger registered browsers on 'savedTodo' topic
    }
}

```

Can be examined in the test-project, too (https://github.com/ClemensSchneider/grails-events-push-tester)

**Comment by mgkimsal** [comment]
I noticed that too - didn't try a closure, but I have event() stuff working like this:

event(topic:"demo",data: "whatever")

Not sure if this helps.

**Comment by fromero** [comment]
smaldini:

"let me test asap"

????

**Comment by aleksandrmelnyk** [comment]
Experiencing same issue. Actually server triggers event, but sent data cannot be modified and  client receives exactly what was sent.
