### ISSUE TITLE
headers?

### ISSUE THREAD

**Issue by mgkimsal** [smaldini/grails-events-push#19]
Not sure if this is more appropriate for some other venue, but I'll try to be specific here.

When an event comes in, it seems it can only be attached to a method on a service, not on a controller.  Is that by design?  Probably is, but it leads to the second question - how do I know what client sent the message in to the event?    

In GrailsServiceActivatingHandler.java there's a _message which has a load of metadata about the incoming message, along with 'payload' (that actual data).  It seems that only payload is getting passed in to the final event handler, not the rest of the 'headers' metadata.  Having that headers metadata would seem like it would be extremely useful - why is that not available? Or is it, and I'm just missing how to get at it?

**Comment by smaldini** [comment]
Looking into that// it's a events-si issue btw

**Comment by sbuettner** [comment]
Maybe you can use the browserFilter-closure in your events config file for that use case:

```
import org.atmosphere.cpr.AtmosphereRequest
import org.grails.plugin.platform.events.EventMessage

def myPushSecurityService = ctx.myPushSecurityService

events = {
    'myPushMessage' browser:true, browserFilter: { EventMessage msg, AtmosphereRequest request ->
        myPushSecurityService.checkPermission(msg, request)
    }
}
```

`AtmosphereRequest` provides access to the request headers/parameters.

**Comment by aro1976** [comment]
would you have a sample of the service myPushSecurityService.checkPermission? 
if you are willing to share I would be very happy to contribute with some more tests and documentation.

**Comment by aro1976** [comment]
@sbuettner didn't work for me, when I setup a simple version of myPushSecurityService (just with logging) I receive the message :

> 2013-06-20 20:57:07,735 [Atmosphere-Shared-DispatchOp-2] WARN  cpr.DefaultBroadcaster  - This message Entry{message=org.grails.plugin.platform.events.push.BroadcastSignal@36bb8d3a, type=ALL, future=org.atmosphere.cpr.BroadcasterFuture@5c8049eb} will be lost

**Comment by aro1976** [comment]
@sbuettner did you make any fancy setup in order to make broserFilter work? which version of Grails/EventsPush/Atmosphere are you using?

**Comment by sbuettner** [comment]
You can access the session of the original request from the `AtmosphereRequest` object. This allows you to verify if a user has the permission to receive a message. The message will then be delivered if your method returns `true`.

**Comment by aro1976** [comment]
@sbuettner today I forked grails-events-push to try some thoughts, specially authenticating user on publishing and listening to events take a look if you are interested https://github.com/aro1976/grails-events-push/commit/04d4d86a1798b85a169d49383ffc7219c2134e8d will document it soon.

**Comment by mpccolorado** [comment]
@sbuettner @aro1976 I have the same problem. I need to know which user is sending the event. Is this possible? Thanks!

**Comment by aro1976** [comment]
Dear martin, take a look at my fork and check whether it works for you!

Enviada do meu iPhone
