### ISSUE TITLE
grails run-app after grails clean causes the reloading agent to fail

### ISSUE THREAD

**Issue by paulcitarella** [smaldini/grails-events-push#24]
With the events-push plugin installed, every time the app is run directly after a clean the reloading agent fails with the following exception.

| Error java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
| Error     at com.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:91)
| Error     at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
| Error     at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
| Error     at java.lang.ClassLoader.defineClass1(Native Method)
| Error     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
| Error     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
| Error     at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
| Error     at com.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:21)
| Error     at com.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1055)
| Error     at com.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:110)
| Error     at com.springsource.loaded.CurrentLiveVersion.<init>(CurrentLiveVersion.java:87)
| Error     at com.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:369)
| Error     at com.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:792)
| Error     at com.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:38)
| Error     at com.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:202)
| Error     at com.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:186)
| Error     at java.lang.Thread.run(Thread.java:680)
| Error Caused by: java.lang.NullPointerException
| Error     at com.springsource.loaded.agent.JVMPlugin.accept(JVMPlugin.java:131)
| Error     at com.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:99)
| Error     at com.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:89)
| Error     ... 16 more

**Comment by smaldini** [comment]
Which Grails version ?

On Wed, Dec 5, 2012 at 7:11 PM, Paul Citarella notifications@github.comwrote:

> With the events-push plugin installed, every time the app is run directly
> after a clean the reloading agent fails with the following exception.
> 
> | Error java.lang.RuntimeException: Reloading agent exited via exception,
> please raise a jira
> | Error at
> com.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:91)
> | Error at
> sun.instrument.TransformerManager.transform(TransformerManager.java:169)
> | Error at
> sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
> | Error at java.lang.ClassLoader.defineClass1(Native Method)
> | Error at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
> | Error at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
> | Error at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
> | Error at
> com.springsource.loaded.ChildClassLoader.defineClass(ChildClassLoader.java:21)
> | Error at
> com.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1055)
> | Error at
> com.springsource.loaded.CurrentLiveVersion.define(CurrentLiveVersion.java:110)
> | Error at
> com.springsource.loaded.CurrentLiveVersion.(CurrentLiveVersion.java:87)
> | Error at
> com.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:369)
> | Error at
> com.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:792)
> | Error at
> com.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:38)
> | Error at
> com.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:202)
> | Error at
> com.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:186)
> | Error at java.lang.Thread.run(Thread.java:680)
> | Error Caused by: java.lang.NullPointerException
> | Error at
> com.springsource.loaded.agent.JVMPlugin.accept(JVMPlugin.java:131)
> | Error at
> com.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:99)
> | Error at
> com.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:89)
> | Error ... 16 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/24.

## 

## _Stéphane_

**Comment by paulcitarella** [comment]
Version 2.1.1

**Comment by zachlendon** [comment]
I see this issue also - why was it closed?

**Comment by zachlendon** [comment]
This issue is fixed by https://github.com/SpringSource/spring-loaded ver. 1.1.2-dev.  1.1.1 does not resolve the issue.  My understanding of the options to work with an updated spring-loaded in a Grails project that uses an older version (ex: 2.1.0) is to either override the springloaded file in $GRAILS_HOME/lib/com.springsource.springloaded/springloaded-core/jars or point to the new file by overriding javaagent/JVM_OPTS on the command-line.  But I'm open to other ideas/suggestions.
