### ISSUE TITLE
Dependencies with org.atmosphere:atmosphere-runtime:1.1.0-SNAPSHOT failed

### ISSUE THREAD

**Issue by MiguelAngel82** [smaldini/grails-events-push#31]
When start the application, with the added plugin in BuliConfig "compile ":events-push:1.0.M7"", it's fail when try to compile it. 

This is te message:

 http://repo1.maven.org/maven2/org/atmosphere/atmosphere-runtime/1.1.0-SNAPSHOT/atmosphere-runtime-1.1.0-SNAPSHOT.jar

```
    ::::::::::::::::::::::::::::::::::::::::::::::

    ::          UNRESOLVED DEPENDENCIES         ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: org.atmosphere#atmosphere-runtime;1.1.0-SNAPSHOT: not found

    ::::::::::::::::::::::::::::::::::::::::::::::
```

I tried to deploy application to probe the plugin, with the only dependencie on this plugin ang Grails 2.2.0 version.

**Comment by smaldini** [comment]
You need to add the codehaus repository mentioned in the plugin page:

mavenRepo "https://oss.sonatype.org/content/repositories/snapshots/"

On Mon, Feb 18, 2013 at 11:22 AM, MiguelAngel82 notifications@github.comwrote:

> When start the application, with the added plugin in BuliConfig "compile
> ":events-push:1.0.M7"", it's fail when try to compile it.
> 
> This is te message:
> 
> http://repo1.maven.org/maven2/org/atmosphere/atmosphere-runtime/1.1.0-SNAPSHOT/atmosphere-runtime-1.1.0-SNAPSHOT.jar
> 
> ```
> ::::::::::::::::::::::::::::::::::::::::::::::
> 
> ::          UNRESOLVED DEPENDENCIES         ::
> 
> ::::::::::::::::::::::::::::::::::::::::::::::
> 
> :: org.atmosphere#atmosphere-runtime;1.1.0-SNAPSHOT: not found
> 
> ::::::::::::::::::::::::::::::::::::::::::::::
> ```
> 
> I tried to deploy application to probe the plugin, with the only
> dependencie on this plugin ang Grails 2.2.0 version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/31.

## 

## _Stéphane_

**Comment by MiguelAngel82** [comment]
Ah ok! Thanks! I haven't seen this... sorry
