### ISSUE TITLE
Failed to resolve dependency when using 

### ISSUE THREAD

**Issue by jpboudreault** [smaldini/grails-events-push#38]
It seems like `org.atmosphere:atmosphere-runtime:1.1.0-SNAPSHOT` is no longer available at `https://oss.sonatype.org/content/repositories/releases/org/atmosphere/atmosphere-runtime/`

There is a `1.1.0.RC1` but when using the dependency stated in the doc `compile ":events-push:1.0.M7"` the `1.1.0-SNAPSHOT` is being used.

**Comment by FaustVs** [comment]
Is there a workaround for this issue? At present its stopping the installation of the plugin completely, it seems.

**Comment by jpboudreault** [comment]
I am certainly no grails expert and I did the following "hack" in order to have it installed and working
- I went into `.grails\ivy-cache\org.grails.plugins\events-push\ivy-1.0.M7.xml` (the file is under your home directory)
- Changed the line <dependency org="org.atmosphere" name="atmosphere-runtime" **rev="1.1.0.RC1"**

If you have a cleaner solution, I would appreciate if you could share it.

Make sure you follow this pull request's sample code since the original documentation seems no longer valid https://github.com/smaldini/grails-events-push/pull/35/files

Also, I had some stability issues when enabling nio so I kept using bio and everything was fine afterwards.

I think that this project only needs a little love at the moment.

**Comment by FaustVs** [comment]
I'm just getting started with Grails too...

Funnily enough, I did actually get it working in the end by adding the following repository entry to BuildConfig.groovy:

mavenRepo "https://oss.sonatype.org/content/repositories/snapshots/"

Cheers for the suggestion also.

**Comment by jpboudreault** [comment]
Closed since the problem was the missing line in BuildConfig.groovy mavenRepo "https://oss.sonatype.org/content/repositories/snapshots/" as suggested by FaustVs
