### ISSUE TITLE
Dependency with Atmosphere-1.1.0-SNAPSHOT failing

### ISSUE THREAD

**Issue by mabd** [smaldini/grails-events-push#39]
Hi, 

recompiling my grails application the following error is shown:

https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/atmosphere-runtime/1.1.0-SNAPSHOT/atmosphere-runtime-1.1.0-20130507.181108-166.jar

https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/atmosphere-runtime/1.1.0-SNAPSHOT/atmosphere-runtime-1.1.0-SNAPSHOT.jar

```
    ::::::::::::::::::::::::::::::::::::::::::::::

    ::          UNRESOLVED DEPENDENCIES         ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: org.atmosphere#atmosphere-runtime;1.1.0-SNAPSHOT: not found

    ::::::::::::::::::::::::::::::::::::::::::::::
```

BuildConfig.groovy contains the entry  mavenRepo "https://oss.sonatype.org/content/repositories/snapshots/".
None of the above mentioned jar-files are in the repository.
a) Is there some errors in the maven-metadata.xml?
b) It is possible to point the plugin to a stable atomosphere version?

Regards
- Marco

**Comment by ClemensSchneider** [comment]
Only in case you did not find a workaround yet:

Grails allows you to exclude a certain dependency from a plugin so you may provide another version:

So in the `plugins` section:

```
compile(":events-push:1.0.M7") {
    excludes 'resources'
    excludes 'atmosphere-runtime'
}
```

And in the `dependencies` section:

```
compile("org.atmosphere:atmosphere-runtime:1.1.0.RC2")
```

**Comment by svaret** [comment]
Shouldn't the plugin page, http://grails.org/plugin/events-push, be updated accordingly? Or is grails-events-push plugin now depending on Atmosphere 2.0.1? I thought I saw 1.1.0-SNAPSHOT being downloaded.

Plugin page updated january 2013 and the push 3 months ago. Just thinking.
