### ISSUE TITLE
unable to download events-push

### ISSUE THREAD

**Issue by kirensk** [smaldini/grails-events-push#66]
Even after giving the below details in the BuildConfig.groovy , The project is failing to resolve the dependencies . Any one have some resolution

Dependency:
compile ":events-push:1.0.M7"
Custom repositories:
mavenRepo "https://oss.sonatype.org/content/repositories/snapshots/"

**Comment by mpccolorado** [comment]
try this: 

```
 repositories {
    ...
    mavenRepo "https://oss.sonatype.org/content/repositories/snapshots"
    mavenRepo "http://repo.grails.org/grails/simple/libs-releases-local"
}

dependencies {
    ...
    compile 'org.grails.plugins:events:1.0.0.M1'
    compile 'org.atmosphere:atmosphere-runtime:2.1.4' //Maybe not necessary
}
```

and

```
plugins {
     ...
     runtime ":events-push:1.0.0.BUILD-SNAPSHOT"
}
```

**Comment by kirensk** [comment]
Thank you for your reply.
There were sill few more unresolved dependency
I have resolved the problem by placing the downloaded zip file with in the project lib folder

Thanks
