### ISSUE TITLE
could requirement to define events in DSL be more of an option ?

### ISSUE THREAD

**Issue by halfbaked** [smaldini/grails-events-push#8]
As can be seen in #6,  I'm trying to find the best way to have user/role constrained events in the application. One way might be to have the topic names reflect this. So there could be a topic: customerAccount_5_supportTicketUpdate, which would indicate a supportTicket has been updated for the customerAccount with id of 5. In this kind of strategy, the topics/event names will be dynamic. Clearly this sort of strategy would not fit with the requirement to hardcode the events. 

Does anyone have any thoughts on this ? Am I looking at it completely wrong ?

**Comment by smaldini** [comment]
I'm trying to think about the less invasive/underperformant solution there. What you need is a dynamic registration of client events (server side event can use the injected "on" methods in controllers/services, like [here](https://github.com/Grailsrocks/grails-platform-core/blob/master/grails-app/controllers/org/grails/plugin/platform/test/SampleController.groovy#L55)).

But in fact what you need is nearly similar to url mapping :
"customerAccount_${id}_supportTicketUpdate" where every similar topic could have the right to dynamically register from the client side. Working on that.

**Comment by smaldini** [comment]
Has been fixed in the last snapshot

**Comment by halfbaked** [comment]
Nice one Stephane. I'll give it a go for my use case. Thanks.

One thing just to add here, is that as I dug deeper into your code, and the Atmosphere documentation it seemed like a Broadcast request filter was really what I needed. There was also some mention of it being more performant. 
I see that platform-core has a form of filtering also for use with the Gorm events. I wonder if some kind of request aware filter could be incorporated somewhere. Typically platform core events are not request aware, so perhaps it would be incorporated into events-push. Then it would be possible to build a security filter that only accepts messages that the current user is authorized to accept. Your knowledge in this area, is obviously a heck of a lot deeper than mine, but I thought I'd throw it out there.

**Comment by smaldini** [comment]
I think this could be done with this kind of syntax, let me know what you think :

``` groovy

'afterInsert' namespace:'gorm', filter:Todo, browser:true, browserFilter: { data, request-> 
//filtering logic, request is the initial suspended req, useful for info such as cookies, session, request attributes
  } 

//like in listeners we could have more infos from events just using EventMessage type
'afterDelete' namespace:'gorm', filter:Todo, browser:true, browserFilter: { EventMessage message, request-> }
```

PlatformCore support extending attributes in the DSL as we want. I think I could add injection from beans if the logic is too complex for a simple closure.

**Comment by halfbaked** [comment]
That looks excellent. That would totally cover my needs.

**Comment by smaldini** [comment]
Pushed and snapshoted : 
https://github.com/smaldini/grails-events-push/commit/443e990cf1a8dfe6db94f3478759ca261cfc3802#L0R27

**Comment by smaldini** [comment]
FYI it uses the atmo filtering system for maximum efficiency

**Comment by halfbaked** [comment]
Stephane, wow! Incredibly fast response. It took me longer to test it! Thank you. Events-push can certainly now accomodate the use case I have been outlining. 

Using the per request broadcast filter was perfect. I have a couple of pieces of feedback. 

1 The broadcast filters enable manipulation of the message. I don't have a need to do this, just something to keep in mind. 

2 My browserFilter closure is included below. It is not the most elegant closure in the world, but it is working! Maybe there are ways to make it more so.

```
def HttpSessionSecurityContextRepository = org.springframework.security.web.context.HttpSessionSecurityContextRepository
 def securityContext = (org.springframework.security.core.context.SecurityContext)request.getSession().getAttribute(HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY);
def personId = securityContext.authentication?.principal.id      
def pass = false
 com.stratus5.auth.Person.withNewSession { session ->
   def person = com.stratus5.auth.Person.get(personId)   
   switch(person){
       case AdminPerson:
          pass=true;break
       case CustomerAccountPerson:
          if (person.customerAccount.id = message.customerAccount.id) pass=true
          else pass=false
          break
       default:
          pass=false;break
   }
  }
return pass
```

Thanks again.
